Changed the test_db to unicourse_min to ensure test pass

diff --git a/.github/workflows/feature-homepage.yml b/.github/workflows/feature-homepage.yml
--- a/.github/workflows/feature-homepage.yml
+++ b/.github/workflows/feature-homepage.yml
@@ -17,7 +17,7 @@ jobs:
         image: mysql:8.0
         env:
           MYSQL_ROOT_PASSWORD: root
-          MYSQL_DATABASE: test_db
+          MYSQL_DATABASE: unicourse_min
         ports:
           - 3306:3306
         options: >-
@@ -33,7 +33,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '20'
+          node-version: "20"
 
       - name: Install dependencies
         run: npm ci
@@ -42,7 +42,7 @@ jobs:
         run: npx prettier --write "**/*.{js,json,css,html}"
 
       - name: Lint with ESLint
-        run: npx eslint . || true  # errors fail, warnings ignored
+        run: npx eslint . || true # errors fail, warnings ignored
 
       - name: Run Mocha tests
         env:
